### ISSUE TITLE
Repo URL gets cut off

### ISSUE THREAD

**Issue by jeffrichiefs** [rusenask/keel#102]
I have my `keel:` settings in `values.yaml`.:
```
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 5m"
  images:
    - repository: "quay.io/repo/app"
      tag: image.dockerTag
```

In the `keel` pod logs I see:
```
kube-system keel-keel-3958146990-5zn02 keel 2017/09/25 18:47:06 warning: destination for settings is a table. Ignoring non-table value <nil>
kube-system keel-keel-3958146990-5zn02 keel time="2017-09-25T18:47:06Z" level=error msg="provider.helm: failed to parse image" error="io/repo/app is not a value" repository_name=quay.io/repo/app repository_tag=image.dockerTag
```
