### ISSUE TITLE
0.0.0 instead of latest

### ISSUE THREAD

**Issue by yuriipolishchuk** [rusenask/keel#96]
Hi!

I run private registry and don't use semver. I want to deploy images with tag `latest` with polling (no webhooks required).

CI also tags every image with build number for example, ${BUILD_ID}=75)

Deployment:
```
metadata:
  name: myapp
  labels:
    keel.sh/policy: force
    keel.sh/trigger: poll
  annotations:
    keel.sh/pollSchedule: "@every 1m"
spec:
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: myregistry.domain/myapp:latest
          imagePullPolicy: Always
          name: myapp
...
```

When new image is pushed to registry there's an entry in the log:
```
time="2017-09-05T12:54:26Z" level=info msg="provider.kubernetes: reseting image for force pull..." deployment=myapp image="myregistry.domain/myapp:0.0.0" namespace=default
```

As a result the image cannot be pulled with `ErrImagePull` error.

Keel image version is 0.4.7

Could you kindly help me with that?
